package com.giao.devlogpulse;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan("com.giao.devlogpulse.mapper")
@EnableScheduling
@EnableAspectJAutoProxy(proxyTargetClass = true)
public class DevLogPulseApplication {

    public static void main(String[] args) {
        SpringApplication.run(DevLogPulseApplication.class, args);
    }

}
